<a href="https://colab.research.google.com/github/Hemanthemu1852/DATASCIENCE-WITH-PYTHON/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
x=np.array([3,4,5])
y=np.array([4,9,7])

In [2]:
import numpy as np

In [4]:
x+y


array([ 7, 13, 12])

In [5]:
a=[1,2,3]
b=[4,5,6]

In [6]:
a+b


[1, 2, 3, 4, 5, 6]

In [7]:
f=np.array([[1,2],[3,4]])

In [8]:
f.ndim

2

In [9]:
x.ndim

1

In [10]:
h=np.matrix([[1,2,3,4],[5,6,7,8]])

In [11]:
h

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [14]:
i=np.matrix([[4,3],[9,8],[2,1],[7,6]])

In [15]:
h*i

matrix([[ 56,  46],
        [144, 118]])

In [16]:
j=np.matrix([[4,3.0],[9,8],[2,1],[7,6]])

In [17]:
j.dtype

dtype('float64')

In [18]:
j.shape

(4, 2)

In [19]:
x.sum()

12

In [20]:
np.sum(x)

12

In [24]:
i.reshape((2,4))

matrix([[4, 3, 9, 8],
        [2, 1, 7, 6]])

In [25]:
i.T

matrix([[4, 9, 2, 7],
        [3, 8, 1, 6]])

In [29]:
j[1,2]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [30]:
np.sqrt(x)

array([1.73205081, 2.        , 2.23606798])

In [31]:
x**2

array([ 9, 16, 25])

In [32]:
x**0.5

array([1.73205081, 2.        , 2.23606798])

In [33]:
np.random.normal()

-0.19272001927624782

In [35]:
x=np.random.normal(size=50)

In [36]:
x

array([-3.58187156e-01,  4.98990762e-02,  1.40739956e+00, -4.96626500e-01,
        1.23945441e-04,  5.45060717e-01,  4.92504899e-01,  3.92728049e-01,
       -1.59187006e+00, -1.04680845e+00,  4.30996332e-01,  1.33713398e-02,
       -7.42185628e-01, -3.89120078e-01, -2.22910587e-01, -3.28331272e-01,
       -2.46118467e-01, -1.08059655e+00, -4.57410485e-01,  1.22018237e+00,
       -5.81039192e-01, -7.65539666e-01, -6.56408374e-01, -1.49239364e+00,
       -5.77367443e-01,  1.67027612e+00,  8.11050356e-01, -1.91097570e-01,
       -2.70578614e-01, -6.36444868e-01,  3.49882594e-01, -4.71581110e-01,
       -1.24977476e+00, -2.34320195e-01,  7.84109115e-02,  1.11863747e+00,
       -5.60867709e-02,  8.89440832e-02,  9.44590670e-01, -1.48625868e-01,
       -6.03493246e-01,  7.19040512e-01, -1.46867104e+00, -6.73739835e-01,
       -3.71815750e-01,  1.53255924e+00, -6.90451813e-01, -1.04184242e-01,
       -3.98818964e-01,  1.73474795e-01])

In [41]:
y= x+np.random.normal(loc=50,scale=1,size=50)

In [42]:
y

array([48.69805103, 52.25611275, 50.99011744, 48.77683409, 49.78403813,
       52.2390571 , 51.49486845, 51.88603937, 48.78294999, 49.47013992,
       48.982013  , 50.14795683, 50.14475464, 51.68169524, 51.95081281,
       50.11796864, 49.44202633, 50.40396924, 48.31602251, 51.28964567,
       51.20674264, 49.05220037, 49.79489956, 47.71193564, 49.18858554,
       52.37607445, 51.27985978, 50.78139778, 49.12544265, 49.1107301 ,
       51.46352764, 49.09989875, 48.55504588, 50.77699383, 50.39100448,
       51.15690404, 50.27660347, 50.73392515, 50.79270508, 47.36802764,
       49.70419329, 50.25770133, 47.86377766, 50.02007582, 50.10028268,
       52.57458588, 49.47423295, 49.72510031, 50.10196265, 49.69794559])

In [43]:
np.corrcoef(x,y)

array([[1.        , 0.66570202],
       [0.66570202, 1.        ]])

In [44]:
rng=np.random.default_rng(1303)

In [45]:
rng

Generator(PCG64) at 0x7E4FE0B0F060

In [46]:
print(rng.normal(scale=5,size=2))

[ 4.09482632 -1.07485605]


In [50]:
#this random seed generates the same results for multiple runs of the code unlike random function
rng2=np.random.default_rng(1303)

In [49]:
print(rng2.normal(scale = 5,size=2))

[ 4.09482632 -1.07485605]


In [51]:
rng = np.random.default_rng(3)

In [52]:
y=rng.standard_normal(10)

In [55]:
np.mean(y),y.mean()

(-0.1126795190952861, -0.1126795190952861)

In [54]:
np.var(y),y.var(),np.mean((y-y.mean())**2)

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

In [57]:
np.sqrt(np.var(y)),np.std(y)

(1.6505576756498128, 1.6505576756498128)

In [59]:
x=rng.standard_normal((10,3))

In [60]:
x

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [61]:
x.mean(axis=0)

array([ 0.15030588,  0.14030961, -0.34238602])

In [62]:
x.mean(0)

array([ 0.15030588,  0.14030961, -0.34238602])